### ISSUE TITLE
Reduce LLVM version matrix a bit?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/heyoka-feedstock#53]
Not sure who in conda-forge would still use LLVM 11,12,13,14 - do we still need them?

**Comment by bluescarni** [comment]
Hi @h-vetinari 

With LLVM providing no API stability across major releases, the sad reality is that several projects are stuck on specific (usually old) LLVM versions. Additionally, it can be quite difficult to make two versions of LLVM coexist in the same process as there is only limited symbol versioning in LLVM and thus there is a high chance of symbol collisions leading to erratic runtime errors.

The large LLVM version matrix is intended to cope with such a situation. With that being said, perhaps if we can make sure that most projects on conda are using, say, LLVM>=13, perhaps it would make sense to remove some builds. Would it be possible to check which LLVM versions are being used in the ecosystem?

**Comment by h-vetinari** [comment]
> Would it be possible to check which LLVM versions are being used in the ecosystem?

I think that's not easy to determine. You can do something like
```
mamba repoquery whoneeds libllvm13 -c conda-forge -p linux-64
```
but that just gives you the users in conda-forge, and more importantly, it doesn't tell you if those have newer versions that depend on newer LLVM, or how the downloads are distributed between them, much less over time.

I mean, this feedstock isn't being rebuilt often, so it's not a big issue. It was more curiosity if you know users that are still on LLVM <14.

**Comment by bluescarni** [comment]
> I mean, this feedstock isn't being rebuilt often, so it's not a big issue. It was more curiosity if you know users that are still on LLVM <14.

I was about to reply numba/llvmlite but I just noticed they finally updated to LLVM 14.

cling is on LLVM 9:

https://github.com/conda-forge/cling-feedstock/blob/main/recipe/meta.yaml

I think I remember reading that the development version of cling is now on LLVM 13, but not sure when that will make its way into conda.

All in all it looks like dropping LLVM 11 and 12 would be reasonable, I would like to try to use this code with cling/xcling one day :)

**Comment by bluescarni** [comment]
I just released a new version and reduced the LLVM matrix to ``[13, 16]``. I'll close this for the time being, feel free to reopen if needed.
